# Optical parameters
[camera]
numerical_aperture = 1.45
refractive_index = 1.52
wavelength = 0.571
pixel_size = 0.1 # μm
period = 10e-6  # seconds
darkcounts = 0.0  # scalar for same value for all pixels, or path to .jld2 file
detector_size = 25  # pixels

# Simulation parameters
[simulation]
n_frames = 6000
diffusion_coefficient = 0.1  # μm²/s
n_particles = 1 #originally ntracks
brightness_multiplier = 1e4 # photons per second
detector_type = "spad" # "spad" or "emccd"
init_width = 0 # ignored when init_bounds_pixels is provided
init_bounds_pixels = [0.0, 12.5, 0.0, 12.5] # [xmin, xmax, ymin, ymax] in detector pixels
random_seed = 26  # false to disable seeding
shift = [9.5, -8.5] # specify x and y shift in pixels, or true for auto-shift, or false for no shift
throw_out_of_bounds = false

# Execution parameters
[saving]
save_location = "../simulations/"
save_unique = false # if true, will save results in folder "$(date)_sim_$(save_name)$(id)" with a unique
# ID at the end if needed to avoid overwriting any results. If false, will save in directory with just "sim_$(save_name)".
save_name = "Fig_S1_D0.1"
 
