# Inference Parameters

# Data directory (relative path to toml file location, or absolute path)
frames_path = "../simulations/sim_Fig_S1_S5_D10.0/frames.jld2"
camera_params_path = "../simulations/sim_Fig_S1_S5_D10.0/sim_params_Fig_S1_S5_D10.0.toml"

# Inference parameters
[inference]
# n_iters = 1024000
n_iters = 1000
size_limit = 1001
parametric = true # if true, number of tracks will remain the same as initial guess
max_n_tracks = 5 # unused if parametric = true
batchsizes = [1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 3000]
# batchsizes = [1, 200, 1000]

# Prior parameters
[priors]
msd_prior = [2, 1e-5]                       # [shape, rate] for gamma prior
diffusion_coeff_guess = 10.0                # μm²/s, set to groundtruth for simulations
brightness_prior = [1, 1]                   # [shape, rate] for gamma prior
brightness_guess = 1e4
brightness_proposal = [10, 1]               # proposal params for brightness
track_prior_scale = 10                      # pixel_size * this for track position prior
track_logonprob = -10
tracks_guess_path = "../simulations/sim_Fig_S1_S5_D10.0/groundtruth.jld2" # path to .jld2 file with initial track guesses

[saving]
chain_output_dir = "../inference_results/"
save_name = "Fig_S1_S5_D10.0"
also_save = [] # list additional files from sim dir (data_dir + simulation_i) to save in chain_output_dir, in addition to the chain files
save_unique = false # if true, will save results in folder "$(date)_inf_$(save_name)$(id)" with a unique
# id at the end if needed to avoid overwriting any results. If false, will save in directory with just "inf_$(save_name)".# 
