# Inference Parameters

# Data paths (relative path to toml file location, or absolute path)
frames_path = "../simulations/sim_Fig_S3_S4_photoblink_55perc_on/frames.jld2"
camera_params_path = "../simulations/sim_Fig_S3_S4_photoblink_55perc_on/sim_params_blink_55perc.toml"

# Inference parameters
[inference]
n_iters = 1024000
size_limit = 1001
parametric = true
max_n_tracks = 1
batchsizes = [1]

# Prior parameters
[priors]
msd_prior = [2, 1e-5]                      # [shape, rate] for gamma prior
diffusion_coeff_guess = 1.0
brightness_prior = [1, 1]                   # [shape, rate] for gamma prior
brightness_guess = 1e4
brightness_proposal = [10, 1]               # proposal params for brightness
track_prior_scale = 10                      # pixel_size * this for track position prior
track_logonprob = -10
tracks_guess_path = "../simulations/sim_Fig_S3_S4_photoblink_55perc_on/groundtruth.jld2" # path to .jld2 file with initial track guesses

[saving]
chain_output_dir = "../inference_results/"
save_name = "Fig_S3_S4_photoblink_55perc_on"
also_save = ["states.jld2"]
save_unique = false
